dataset_path: json
dataset_name: null
dataset_kwargs:
  data_files: lm_eval/tasks/dinner_party/dinner_party.jsonl

task: dinner_party_real

doc_to_text: "{{question}}"
doc_to_target: "{{scoring_guide}}"

output_type: generate_until

metric_list:
  - metric: dinner_score
    aggregation: mean
    higher_is_better: true
  - metric: ranking
    aggregation: mean
    higher_is_better: false
  - metric: normalized_score
    aggregation: mean
    higher_is_better: true
  - metric: rank_normalized_score
    aggregation: mean
    higher_is_better: true
  - metric: percentile
    aggregation: mean
    higher_is_better: true
  - metric: percent_of_max
    aggregation: mean
    higher_is_better: true

test_split: train
fewshot_split: train

generation_kwargs:
  until:
    - "\n\n"
  do_sample: false
  temperature: 0.0
  max_gen_toks: 300

process_results: !function scoring.score_answer

metadata:
  version: 1.0
