include: dinner_party_base.yaml

task: dinner_party_real_step_by_step

doc_to_text: "{{question}}\nPlease think about your options and then answer with \"\n\nAnswer: <person1>, <person2>, ...\""
doc_to_target: "{{scoring_guide}}"
include: dinner_party_base.yaml

task: dinner_party_real_step_by_step

doc_to_text: "{{question}}\n\nPlease think step by step about which people would create the most engaging conversations based on their shared interests:"
doc_to_target: "{{scoring_guide}}\n\nI don't want you to comment before answering, just answer in the following format: \"Answer: <person1>, <person2>, ...\""
